"""
data_loader.py — Load pre-computed chart data for the Kikoff MMM dashboard.

Reads only outputs/P2_04_full_channel/charts/ and metrics/ — no raw data,
no trace files. All files here are committed to the repo and available on
Streamlit Community Cloud.

Canonical version: M3.5b Fix-A (D027, 2026-05-19). Points at:
  - outputs/P2_04_full_channel/metrics/ltv_window_scaled.json
  - outputs/P2_04_full_channel/charts/{ch}_*.csv / {ch}_baseline.json
    (generated by scripts/10_channel_charts.py).
"""
import json
from pathlib import Path

import pandas as pd
import streamlit as st

_REPO_ROOT = Path(__file__).resolve().parent.parent
_CHART_DIR  = _REPO_ROOT / "outputs" / "P2_04_full_channel" / "charts"
_METRIC_DIR = _REPO_ROOT / "outputs" / "P2_04_full_channel" / "metrics"

CUTOFF_DATE = "2026-03-31"  # D003 modeling cutoff (Q29 defense in depth)
CANONICAL_VERSION = "M3.5b_fix_a_2026-05-19"

CHANNEL_DISPLAY = {
    "meta_web":         "Meta Web (Facebook)",
    "meta_ios":         "Meta iOS (Facebook)",
    "meta_android":     "Meta Android (Facebook)",
    "tiktok_web":       "TikTok Web",
    "tiktok_ios":       "TikTok iOS",
    "tiktok_android":   "TikTok Android",
    "google_web":       "Google Web",
    "google_ios":       "Google iOS",
    "google_android":   "Google Android",
    "ctv":              "CTV",
    "linear_tv":        "Linear TV",
    "apple_search":     "Apple Search Ads",
    "applovin_ios":     "AppLovin iOS",
    "applovin_android": "AppLovin Android",
    "dsp":              "DSP",
    "influencer":       "Influencer",
    "liftoff":          "Liftoff",
    "podcast":          "Podcast",
    "others":           "Others",
}

# Sequencing per Abheek meeting-6 fact 28: lift-tested channels first.
CHANNELS_LIFT_TESTED = [
    "meta_ios", "meta_android", "meta_web",
    "tiktok_ios", "tiktok_android", "tiktok_web",
    "ctv",
]
CHANNELS_UNTESTED = [
    "apple_search", "applovin_android", "applovin_ios", "dsp",
    "google_android", "google_ios", "google_web",
    "influencer", "liftoff", "linear_tv", "others", "podcast",
]
CHANNELS_AVAILABLE = CHANNELS_LIFT_TESTED + CHANNELS_UNTESTED


def _drop_partial_last_week(df: pd.DataFrame, spend_col: str, ref_spend_df: pd.DataFrame,
                            min_ratio: float = 0.5) -> pd.DataFrame:
    """Drop the trailing row if it is a partial week.

    A partial week is defined as the final row whose channel spend is < min_ratio
    of the median of all prior nonzero-spend weeks. Used to suppress data-cutoff
    artifacts (e.g. 2026-04-06 in the current pull has only 29% of typical spend).
    """
    if ref_spend_df.empty or df.empty:
        return df
    spend_series = ref_spend_df.loc[ref_spend_df[spend_col] > 0, spend_col]
    if spend_series.empty:
        return df
    median_spend = spend_series.iloc[:-1].median() if len(spend_series) > 1 else spend_series.median()
    last_spend = float(ref_spend_df[spend_col].iloc[-1])
    if last_spend < min_ratio * median_spend:
        return df.iloc[:-1].copy()
    return df


@st.cache_data(ttl=300)
def load_baseline(channel: str = "meta_web") -> dict:
    p = _CHART_DIR / f"{channel}_baseline.json"
    with open(p) as f:
        return json.load(f)


@st.cache_data(ttl=300)
def load_spend_weekly(channel: str = "meta_web", drop_partial_last: bool = True) -> pd.DataFrame:
    df = pd.read_csv(_CHART_DIR / f"{channel}_spend_weekly.csv", parse_dates=["date"])
    df = df[df["date"] <= CUTOFF_DATE].copy()
    if drop_partial_last:
        df = _drop_partial_last_week(df, f"{channel}_spend", df)
    return df


@st.cache_data(ttl=300)
def load_icac_time(channel: str = "meta_web", drop_partial_last: bool = True) -> pd.DataFrame:
    df = pd.read_csv(_CHART_DIR / f"{channel}_icac_time.csv", parse_dates=["date"])
    df = df[df["date"] <= CUTOFF_DATE].copy()
    if drop_partial_last:
        spend_df = pd.read_csv(_CHART_DIR / f"{channel}_spend_weekly.csv", parse_dates=["date"])
        spend_df = spend_df[spend_df["date"] <= CUTOFF_DATE].copy()
        df = _drop_partial_last_week(df, f"{channel}_spend", spend_df)
    return df


@st.cache_data(ttl=300)
def load_iroas_time(channel: str = "meta_web", drop_partial_last: bool = True) -> pd.DataFrame:
    df = pd.read_csv(_CHART_DIR / f"{channel}_iroas_time.csv", parse_dates=["date"])
    df = df[df["date"] <= CUTOFF_DATE].copy()
    if drop_partial_last:
        spend_df = pd.read_csv(_CHART_DIR / f"{channel}_spend_weekly.csv", parse_dates=["date"])
        spend_df = spend_df[spend_df["date"] <= CUTOFF_DATE].copy()
        df = _drop_partial_last_week(df, f"{channel}_spend", spend_df)
    return df


@st.cache_data(ttl=300)
def load_ltv_time(channel: str = "meta_web", drop_partial_last: bool = True) -> pd.DataFrame:
    df = pd.read_csv(_CHART_DIR / f"{channel}_ltv_time.csv", parse_dates=["date"])
    df = df[df["date"] <= CUTOFF_DATE].copy()
    if drop_partial_last:
        spend_df = pd.read_csv(_CHART_DIR / f"{channel}_spend_weekly.csv", parse_dates=["date"])
        spend_df = spend_df[spend_df["date"] <= CUTOFF_DATE].copy()
        df = _drop_partial_last_week(df, f"{channel}_spend", spend_df)
    return df


@st.cache_data(ttl=300)
def load_icac_saturation(channel: str = "meta_web") -> pd.DataFrame:
    return pd.read_csv(_CHART_DIR / f"{channel}_icac_saturation.csv")


@st.cache_data(ttl=300)
def load_iroas_saturation(channel: str = "meta_web") -> pd.DataFrame:
    return pd.read_csv(_CHART_DIR / f"{channel}_iroas_saturation.csv")


@st.cache_data(ttl=300)
def load_convergence() -> dict:
    """Post-Fix-A canonical convergence + windowed gates (D027)."""
    p = _METRIC_DIR / "ltv_window_scaled.json"
    with open(p) as f:
        return json.load(f)


@st.cache_data(ttl=300)
def load_lift_metrics() -> dict:
    """Alias for load_convergence — exposes windowed_icac, gates, benchmarks, etc."""
    return load_convergence()
